version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
dependency_file_paths = ["package.json"]
environment = ["nodejs", "browser"]
module_system = "commonjs"
enabled = true