# ass Docker compose.yaml v0.1.0
# authors:
#  - tycrek <t@tycrek.com> (https://tycrek.com/)
#  - Zusier <zusier@pm.me> (https://github.com/Zusier)

services:
  ass:
    build: .
    command: npm start
    container_name: ass-docker
    restart: unless-stopped
    ports:
      - "40115:40115"
      - "45375:45375"
    volumes:
      - ./uploads:/opt/ass/uploads
      - ./config.json:/opt/ass/config.json
      - ./auth.json:/opt/ass/auth.json
      - ./data.json:/opt/ass/data.json
      - ./share:/opt/ass/share
    tmpfs: /tmp # temp files such as uploads are stored here
    working_dir: /opt/ass # this is where the ass files are located within the container
    tty: true
    environment:
      - NODE_ENV=production # for production
      - ASS_ENV=docker # docker, local, production (not widely used yet)
      - LOG_LEVEL=debug # debug, info, warn, error
      - FORCE_COLOR=3 # force colour output